### ISSUE TITLE
Change API to not require store reference

### ISSUE THREAD

**Issue by markerikson** [luwes/redux-eagle#1]
The current implementation of `watch` is:

```js
export function watch(store, selectors, listener, compare = defaultCompare) {
  return store.dispatch({
    type: WATCH,
    payload: { selectors, listener, compare }
  })
}
```

This is unnecessarily restrictive, as it requires a reference to the store in order to use it.  Instead, this should be a plain action creator:

```js
export function watch(selectors, listener, compare = defaultCompare) {
  return {
    type: WATCH,
    payload: { selectors, listener, compare }
  }
}
```

That way, it can be bound up and dispatched by any connected component:

```js
import {watch} from "redux-eagle";

const actions = {watch};

export default connect(null, actions)(MyComponent);

// use this.props.watch() inside the component
```

**Comment by luwes** [comment]
Thanks for the great feedback @markerikson! Gonna change this right away.

I was building this for a React-less project.
It would still be nice to not have to bind the action creators every time for non-React projects.

**Comment by markerikson** [comment]
Sure, but I'd still suggest keeping the action creators unaware of the store by themselves.  Leave that up to the UI layer to worry about, even if it's done via `import {bindActionCreators} from "redux"`.
